---
- hosts: all
  gather_facts: False
  vars_files:
    - domains.yml
  tasks:
  - name: start service local nagios
    service:
      name: nagios3
      state: started
  - name: add configs to conf.d/tls/
    template:
      src: tls_ch_4_nag.j2
      dest: /etc/nagios3/conf.d/tls/{{ item }}.cfg
      mode: 0644
    with_items: '{{ domains }}'
  - name: reload local nagios
    service:
      name: nagios3
      state: reloaded
    notify:
      - stop service local nagios
      - sync external nagios and reload
  handlers:
    - name: stop service local nagios
      service:
        name: nagios3
        state: stopped
    - name: sync external nagios and reload
      command: /etc/nagios3/sync.sh
